### ISSUE TITLE
Rename "user" to "username" in authentication requests

### ISSUE THREAD

**Issue by Patralos** [janoszen/containerssh#25]
Currently the post request contains:

{
    "**user**": "username",
    "remoteAddress": "127.0.0.1:1234",
    "sessionId": "A base64 SSH session ID",
    "passwordBase64": "Base 64 password"
}

{
  "**username**":"ssh username",
  "sessionId": "ssh session ID"
}

I would suggest to either use username or user, to avoid confusion.

**Comment by janoszen** [comment]
Your change has been added. The authentication requests (password and pubkey) now send an additional `username` field next to the `user` field. The `user` field will be removed in a later release so all users are urged to update their authentication server implementation.
