### ISSUE TITLE
Option to disable Exec Requests

### ISSUE THREAD

**Issue by Patralos** [janoszen/containerssh#33]
An option to disable or block "Exec Requests" would be great, as this would allow additional use cases, where a user is forced into a "command" / shell(Entrypoint) and can´t escape it. 
Currently it is possible to bypass any Entrypoint using `ssh -f 'command'`.

**Comment by janoszen** [comment]
The execution of user-initiated commands can now be disabled in version [0.2.1](https://github.com/janoszen/containerssh/releases/tag/0.2.1) as follows:

```
dockerrun:
    config:
        disableCommand: true
```

```
kuberun:
    pod:
        disableCommand: false
```
